# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-sla-sa
  namespace: ${NAMESPACE}
imagePullSecrets:
  - name: nvcr-imagepullsecret
