# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nixl-benchmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nixl-benchmark
  template:
    metadata:
      labels:
        app: nixl-benchmark
    spec:
      imagePullSecrets:
        - name: nvcrimagepullsecret
      containers:
      - name: nixl-benchmark
        image: nvcr.io/nvidian/nim-llm-dev/vllm-runtime:nixlbench-e42c07a8
        command: ["sh", "-c"]
        args:
          - "nixlbench -etcd_endpoints http://dynamo-platform-etcd:2379 --target_seg_type VRAM --initiator_seg_type VRAM && sleep infinity"
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
